class Constant():
    TILE_SIZE = 48
    WIN_SIZE = (800, 600)
    CAMERA_OFFSET = (50, 50)
    PLAYER_SIZE = (TILE_SIZE, TILE_SIZE)
    DEFAULT_SIZE = (TILE_SIZE, TILE_SIZE)
    MOVE_LIMIT = 100
    DEFAULT_ACT_RADIUS = 10 * TILE_SIZE
    FPS = 60